backend:
  name: github
  branch: main 
  repo: enigmalea/enigmalea.quest

# These lines should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads

publish_mode: editorial_workflow
site_url: https://www.enigmalea.quest

collections:
- name: log
  label: "update log"
  folder: blog
  description: "Site update log."
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
    - label: "Tags"
      name: "tags"
      widget: "list"
    - label: "Authors"
      name: "authors"
      widget: hidden
      default: "enig"

- name: dragonage
  label: "DA resources"
  folder: "docs/DA"
  description: "Dragon Age resources pages."
  identifier_field: "label"
  extension: md
  widget: "list"
  create: true
  slug: "{{slug}}" # Filename template, e.g., title.md
  fields:
    - { name: label, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }

- name: vault
  label: "Vault"
  folder: "docs/Vault"
  description: "Wiki/knowledge bank pages."
  identifier_field: "label"
  extension: md
  widget: "list"
  create: true
  slug: "{{slug}}" # Filename template, e.g., title.md
  fields:
    - { name: label, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }